"""APS Extension SDK v1 public surface.

This package is a contract-only, dependency-free SDK skeleton.  It contains no
Runtime loader, Solver adapter, database access, HTTP surface, or Developer Kit.
"""

from aps_extension_sdk.errors import (
    ERROR_NAMESPACE,
    ERROR_REGISTRY_VERSION,
    ExtensionContractError,
    ExtensionErrorCode,
)
from aps_extension_sdk.manifest import (
    EXTENSION_COMPATIBILITY_VERSION,
    EXTENSION_MANIFEST_VERSION,
    REGISTRY_PROTOCOL_VERSION,
    SDK_API_VERSION,
    CompatibilityPolicy,
    ContributionManifest,
    ExecutionDomain,
    ExtensionManifest,
    ExtensionPoint,
    ObjectiveStage,
    RegistryResolution,
    parse_compatibility_policy,
    parse_extension_manifest,
    resolve_manifest_set,
)
from aps_extension_sdk.protocols import (
    PROTOCOLS_BY_POINT,
    Constraint,
    ConstraintContext,
    ConstraintOutput,
    ExtensionInputView,
    Objective,
    ObjectiveContext,
    ObjectiveOutput,
    ObjectiveSense,
    PlanningRule,
    PlanningRuleContext,
    PlanningRuleOutput,
    PluginRegistry,
    ReplanAction,
    ReplanContext,
    ReplanDecision,
    ReplanPolicy,
    ValidationContext,
    ValidationOutput,
    ValidationRule,
    ValidationViolation,
    validate_protocol_output,
)
from aps_extension_sdk.values import (
    FrozenJsonObject,
    SemanticVersion,
    VersionInterval,
    assert_immutable_json,
    canonical_json_bytes,
    fingerprint_json,
    freeze_json,
    thaw_json,
)


SDK_RELEASE_STATUS = "CONTRACT_ONLY_NOT_DISTRIBUTED"

__all__ = [
    "ERROR_NAMESPACE",
    "ERROR_REGISTRY_VERSION",
    "EXTENSION_COMPATIBILITY_VERSION",
    "EXTENSION_MANIFEST_VERSION",
    "PROTOCOLS_BY_POINT",
    "REGISTRY_PROTOCOL_VERSION",
    "SDK_API_VERSION",
    "SDK_RELEASE_STATUS",
    "CompatibilityPolicy",
    "Constraint",
    "ConstraintContext",
    "ConstraintOutput",
    "ContributionManifest",
    "ExecutionDomain",
    "ExtensionContractError",
    "ExtensionErrorCode",
    "ExtensionInputView",
    "ExtensionManifest",
    "ExtensionPoint",
    "FrozenJsonObject",
    "Objective",
    "ObjectiveContext",
    "ObjectiveOutput",
    "ObjectiveSense",
    "ObjectiveStage",
    "PlanningRule",
    "PlanningRuleContext",
    "PlanningRuleOutput",
    "PluginRegistry",
    "RegistryResolution",
    "ReplanAction",
    "ReplanContext",
    "ReplanDecision",
    "ReplanPolicy",
    "SemanticVersion",
    "ValidationContext",
    "ValidationOutput",
    "ValidationRule",
    "ValidationViolation",
    "validate_protocol_output",
    "VersionInterval",
    "assert_immutable_json",
    "canonical_json_bytes",
    "fingerprint_json",
    "freeze_json",
    "parse_compatibility_policy",
    "parse_extension_manifest",
    "resolve_manifest_set",
    "thaw_json",
]
