"""Pure domain contract types for the executable specification."""

from .capabilities import (
    CAPABILITY_STATUS_BY_NAME,
    CapabilityContractError,
    CapabilityName,
    CapabilityStatus,
    require_v1_capability_contract,
)
from .errors import (
    ERROR_CATEGORY_BY_CODE,
    ProductErrorCategory,
    ProductErrorCode,
    category_for_error_code,
)
from .canonical_records import (
    COLLECTION_ID_FIELDS,
    CanonicalContractError,
    CanonicalRecordsDocument,
    ImportPackageDocumentV2,
    OperationInstanceDocument,
    OperationPrecedenceEdgeDocument,
    OperationResourceOptionDocument,
    PlanningSnapshotDocumentV2,
    SourceReference,
    SyntheticProvenance,
    validate_canonical_records,
    validate_import_package_v2,
    validate_planning_snapshot_v2,
)
from .types import (
    CanonicalId,
    ContractValueError,
    DurationSeconds,
    TickSeconds,
    canonical_id,
    duration_to_ticks,
    format_utc_instant,
    parse_utc_instant,
    require_duration_seconds,
    require_tick_seconds,
    require_utc,
)
from .validation import (
    ContractViolation,
    validate_planning_problem_contract,
    validate_snapshot_contract,
)
from .schedule_version import (
    ReviewableScheduleDocuments,
    SCHEDULE_VERSION_LIFECYCLE_VERSION,
    ScheduleVersionCreationContext,
    ScheduleVersionLifecycleError,
    ScheduleVersionLifecycleFailure,
    ValidatedPlanningOutput,
    build_reviewable_schedule_documents,
)

__all__ = [
    "CAPABILITY_STATUS_BY_NAME",
    "COLLECTION_ID_FIELDS",
    "CanonicalId",
    "CanonicalContractError",
    "CanonicalRecordsDocument",
    "ContractValueError",
    "ContractViolation",
    "CapabilityContractError",
    "CapabilityName",
    "CapabilityStatus",
    "DurationSeconds",
    "ERROR_CATEGORY_BY_CODE",
    "ImportPackageDocumentV2",
    "OperationInstanceDocument",
    "OperationPrecedenceEdgeDocument",
    "OperationResourceOptionDocument",
    "PlanningSnapshotDocumentV2",
    "ProductErrorCategory",
    "ProductErrorCode",
    "ReviewableScheduleDocuments",
    "SCHEDULE_VERSION_LIFECYCLE_VERSION",
    "ScheduleVersionCreationContext",
    "ScheduleVersionLifecycleError",
    "ScheduleVersionLifecycleFailure",
    "TickSeconds",
    "ValidatedPlanningOutput",
    "SourceReference",
    "SyntheticProvenance",
    "canonical_id",
    "category_for_error_code",
    "build_reviewable_schedule_documents",
    "duration_to_ticks",
    "format_utc_instant",
    "parse_utc_instant",
    "require_duration_seconds",
    "require_tick_seconds",
    "require_utc",
    "require_v1_capability_contract",
    "validate_canonical_records",
    "validate_import_package_v2",
    "validate_planning_problem_contract",
    "validate_planning_snapshot_v2",
    "validate_snapshot_contract",
]
