import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "@playwright/test";

const exchange = process.env.P9_EXCHANGE!;
const read = (name: string) => JSON.parse(readFileSync(join(exchange, name), "utf8"));

test("real Runtime denies a missing session visibly", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("plantnexus.locale.v1", "en-US"));
  await page.goto(`/planning/versions/${read("bootstrap.json").base.schedule_version_id}`);
  await expect(page.getByText("Authorization denied", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve version" })).toHaveCount(0);
});

test("real Runtime event, trusted projection, asynchronous replan and explicit review", async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem("plantnexus.locale.v1", "en-US");
    Object.assign(window, { __PLANTNEXUS_APS_SESSION_PROVIDER__: { getAccessToken: async () => "p9-test-token" } });
  });
  const bootstrap = read("bootstrap.json");
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const comparison = page.waitForResponse((response) => response.url().endsWith("/schedule-version-comparisons"));
  await page.goto(`/compare?schedule_version_id=${bootstrap.base.schedule_version_id}&compared_schedule_version_id=${bootstrap.compared.schedule_version_id}`);
  expect((await comparison).status()).toBe(200);
  await expect(page.getByText("Contract error", { exact: true })).toHaveCount(0);
  await page.goto(`/planning/versions/${bootstrap.manual.schedule_version_id}`);
  await page.getByRole("combobox", { name: "Manual operation" }).click();
  await page.getByRole("option", { name: bootstrap.assignment.operation_id, exact: true }).click();
  const shifted = (value: string) => new Date(Date.parse(value) + 600_000).toISOString().replace(".000Z", "Z");
  await page.getByLabel("Start UTC", { exact: true }).fill(shifted(bootstrap.assignment.start_at_utc));
  await page.getByLabel("End UTC", { exact: true }).fill(shifted(bootstrap.assignment.end_at_utc));
  await page.getByLabel("Change reason").fill("Move synthetic operation after review");
  const movedResponse = page.waitForResponse((response) => response.url().endsWith("/commands") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Move selected operation" }).click();
  const moved = await (await movedResponse).json();
  await page.goto(`/planning/versions/${moved.new_version.schedule_version_id}`);
  await page.getByLabel("Submission reason").fill("Review synthetic manual adjustment");
  await page.getByRole("button", { name: "Submit for review", exact: true }).click();
  await expect(page.getByText("READY_FOR_REVIEW", { exact: true })).toBeVisible();
  await page.goto("/planning/replanning");
  async function submit(document: object | string, key: string) {
    await page.getByLabel("Canonical submission").fill(typeof document === "string" ? document : JSON.stringify(document));
    await page.getByLabel("Submission idempotency key").fill(key);
    await page.getByRole("checkbox", { name: "Confirm submission to the current Simulation Runtime" }).check();
    await page.getByRole("button", { name: "Submit to Runtime", exact: true }).click();
    await expect(page.getByText("Runtime acknowledgement", { exact: true })).toBeVisible();
    return JSON.parse(await page.getByTestId("submission-result").innerText());
  }
  const event = await submit(bootstrap.event, "p9-browser-event-001");
  expect(event.replayed).toBe(false);
  writeFileSync(join(exchange, "event-accepted"), "accepted");
  await expect.poll(() => existsSync(join(exchange, "request.json"))).toBe(true);
  const request = read("request.json");
  const queued = await submit(readFileSync(join(exchange, "request.json"), "utf8"), "p9-browser-replan-001");
  expect(queued.result.attempt.state).toBe("CREATED");
  const params = new URLSearchParams({ planning_scope_id: request.planning_scope_id, authority_id: request.event_stream.authority.authority_id, stream_id: request.event_stream.source_stream.stream_id, stream_version: request.event_stream.source_stream.stream_version, from_position: "1", through_position: "1", request_id: request.request_id, request_fingerprint: request.request_fingerprint, attempt_id: queued.result.attempt.attempt_id });
  await page.goto(`/planning/replanning?${params}`);
  await page.getByLabel("Action reason").fill("Cancel before synthetic worker dispatch");
  await page.getByRole("checkbox", { name: "I understand this acts only on the current Simulation PlanningRun attempt." }).check();
  await page.getByRole("button", { name: "Cancel current attempt", exact: true }).click();
  await expect(page.getByText("CANCELLED", { exact: true }).first()).toBeVisible();
  await page.getByLabel("Action reason").fill("Retry cancelled synthetic attempt");
  const retryResponse = page.waitForResponse((response) => response.url().endsWith("/retry"));
  await page.getByRole("button", { name: "Retry terminal attempt", exact: true }).click();
  const retried = await (await retryResponse).json();
  expect(retried.result.attempt.attempt_number).toBe(2);
  writeFileSync(join(exchange, "attempt.json"), JSON.stringify(retried.result.attempt));
  await expect.poll(() => existsSync(join(exchange, "completed.json")), { timeout: 30_000 }).toBe(true);
  const report = read("completed.json");
  params.set("attempt_id", retried.result.attempt.attempt_id);
  await page.goto(`/planning/replanning?${params}`);
  await expect(page.getByText("COMPLETED", { exact: true }).first()).toBeVisible();
  const identity = report.new_schedule_version.schedule_version_id;
  await page.goto(`/planning/versions/${identity}`);
  await expect(page.getByText("replan-candidate.v1", { exact: true })).toBeVisible();
  await page.getByLabel("Submission reason").fill("Review verified synthetic replan");
  await page.getByRole("button", { name: "Submit for review", exact: true }).click();
  await expect(page.getByText("READY_FOR_REVIEW", { exact: true })).toBeVisible();
  await page.getByLabel("Decision reason").fill("Approve verified synthetic replan");
  await page.getByRole("button", { name: "Approve version" }).click();
  await expect(page.getByText("APPROVED", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Review internal publication" }).click();
  const dialog = page.getByRole("dialog", { name: "Confirm SIMULATION_INTERNAL publication" });
  await dialog.getByLabel("Current published version ID").fill(bootstrap.base.schedule_version_id);
  await dialog.getByLabel("Publication reason").fill("Publish approved synthetic successor");
  await dialog.getByRole("checkbox").check();
  await dialog.getByRole("button", { name: "Publish internally" }).click();
  await expect(page.getByText("PUBLISHED", { exact: true })).toBeVisible();
  await page.goto(`/planning/versions/${moved.new_version.schedule_version_id}`);
  await page.getByLabel("Decision reason").fill("Approve synthetic manual adjustment");
  await page.getByRole("button", { name: "Approve version" }).click();
  await expect(page.getByText("APPROVED", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Review internal publication" }).click();
  await dialog.getByLabel("Current published version ID").fill(identity);
  await dialog.getByLabel("Publication reason").fill("Publish reviewed manual successor");
  await dialog.getByRole("checkbox").check();
  await dialog.getByRole("button", { name: "Publish internally" }).click();
  await expect(page.getByText("PUBLISHED", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
